simple_blog/posts/urls.py
"""Posts URLs."""

# Django
from django.urls import path


# Views
from posts import views

urlpatterns = [
    path(
        route='noticias',
        view=views.PostsFeedView.as_view(template_name='noticias.html'),
        name='noticias'
    ),

    path(
        route='',
        view=views.PostsFeedView.as_view(template_name='index.html'),
        name='index'
    ),
    path(
        route='posts/<slug:url>/',
        view=views.PostDetailView.as_view(),
        name='detail'
    ),
    path(
        route='posts/save_comment',
        view=views.save_comment,
        name='save_comment'
    ),

]

simple_blog/simple_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings
from posts.views import searchBlog


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path(
        route='noticias',
        view=TemplateView.as_view(template_name='noticias.html'),
        name='noticias'
    ),
    path(
        route='',
        view=TemplateView.as_view(template_name='index.html'),
        name='index'
    ),
    path(
        route='institucional',
        view=TemplateView.as_view(template_name='about.html'),
        name='about'
    ),
    path(
        route='categorias',
        view=TemplateView.as_view(template_name='categorias.html'),
        name='categorias'
    ),
    path(
        route='contacto',
        view=TemplateView.as_view(template_name='contacto.html'),
        name='contacto'
    ),
    path('', include(('users.urls', 'users'), namespace='users')),

    path("q/", searchBlog, name='search'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simple_blog/posts/models.py
"""Posts models."""

#Acá se arma la estructura de la base de datos de posts (o noticias)

# Django
from django.db import models

from django.utils.text import slugify
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from categories.models import Category

class Post(models.Model):
    """Post model."""
    
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    profile = models.ForeignKey('users.Profile', on_delete=models.PROTECT)

    title = models.CharField(max_length=255)
    image_header = models.ImageField(upload_to='posts/photos')
    post = RichTextField()

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    is_draft = models.BooleanField(default=True)
    url = models.SlugField(max_length=255, unique=True)
    views = models.PositiveIntegerField(default=0)
    categories = models.ManyToManyField(Category)

    class Meta:
        ordering = ('title',)


    def __str__(self):
        """Return title and username."""
        return '{} by @{}'.format(self.title, self.user.username)


    def save(self, *args, **kwargs):
        self.url = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

simple_blog/posts/views.py
from django.shortcuts import render, redirect
from django.views.generic import DetailView, ListView
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

# Models
from posts.models import Post
from categories.models import Category
from comments.models import Comment
from django.db.models import Q 

# Forms
from comments.forms import CreateCommentForm


class PostsFeedView(ListView):
    """Index."""
    template_name = 'posts/index.html'
    model = Post
    ordering = ('-created',)
    paginate_by = 10
    context_object_name = 'posts'
    queryset = Post.objects.filter(is_draft=False)

    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context

    
class PostDetailView(DetailView):
    """Detail post."""
    template_name = 'posts/detail.html'
    model = Post
    context_object_name = 'post'
    slug_field = 'url'
    slug_url_kwarg = 'url'


    def get_queryset(self):
        return Post.objects.filter(is_draft=False)

    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['comments'] = Comment.objects.filter(post=self.get_object()).all()
        context['form_comments'] = CreateCommentForm()
        return context


@login_required
def save_comment(request):
    if request.method == 'POST':
        url = request.POST['url']
        post = {
            'user': request.user.id,
            'profile': request.user.id,
            'comment': request.POST['comment'],
            'post': request.POST['post']
        }
        form = CreateCommentForm(post)
        if form.is_valid():
            form.save()
            return redirect('posts:detail', url=url)
    else:
        return HttpResponse(status=405)
    return HttpResponse(status=500)


def searchBlog(request): 
    context = {} 
    posts = Post.objects.all() 
    if request.method == "GET": 
        query = request.GET.get("search") 
        queryset = posts.filter(Q(title__icontains=query))
        total = queryset.count() 
        context.update({ 
            "total":total, 
            "query":query, 
            "posts":queryset, 
 
        }) 
 
        return render(request, "search-results.html", context) 

simple_blog/templates/posts/detail.html
{% extends "base.html" %}
{% block title %}{{post.title}}{% endblock title %}

{% block content %}

        <!-- Blog post -->
        <section class="blog-post section-header-offset">

            <div class="blog-post-container container">
              
              <div class="blog-post-data">
                <h3 class="title blog-post-title">{{post.title}}</h3>
                <div class="article-data">
                  <span class="article-data-date">{{post.created}}</span>
                </div>
                <img src="{{ post.image_header.url }}" alt="">
              </div>
              
              <div class="container">
                
                {{post.post|safe}}
              
              </div>
            </div>
           
            {% if user.is_authenticated %}

            <div class="card my-4">
              <h5 class="card-header">Deja un comentario:</h5>
              <div class="card-body">
                <form method="POST" action="{% url "posts:save_comment" %}">
                  {% csrf_token %}
                  <input type="hidden" name="url" value="{{post.url}}" />
                  <input type="hidden" name="post" value="{{post.id}}" />
                  <div class="form-group">
                    <textarea class="form-control" name="comment" rows="3"></textarea>
                  </div>
                  <button type="submit" class="btn btn-primary">Enviar</button>
                </form>
              </div>
            </div>
            {% endif %}
            
            {% for comment in comments %}
            <div class="media mb-4">

              {% if comment.user.profile.photo %}
              <img class="d-flex mr-3 rounded-circle" width="50px" height="50px" src="/media/{{ comment.user.profile.photo }}" alt="">
              
              {% else %}
              
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              {% endif %}
              
              <div class="media-body">
                
                <h5 class="mt-0">{{comment.user.username}}</h5>
                {{comment.comment}}
              </div>
            </div>
            {% endfor %}
          </section>


  {% comment %} <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <h1 class="mt-4">{{post.title}}</h1>
        <p class="lead">
          por 
          <a href="#">{{post.user.username}}</a>
        </p>
        <hr>
        <p>Escrito el {{post.created}}</p>
        <hr>
        <img class="img-fluid rounded" src="{{ post.image_header.url }}" alt="">
        <hr>
        <p class="lead">{{post.post|safe}}</p>
        <hr>
        {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Deja un comentario:</h5>
          <div class="card-body">
            <form method="POST" action="{% url "posts:save_comment" %}">
              {% csrf_token %}
              <input type="hidden" name="url" value="{{post.url}}" />
              <input type="hidden" name="post" value="{{post.id}}" />
              <div class="form-group">
                <textarea class="form-control" name="comment" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Enviar</button>
            </form>
          </div>
        </div>
        {% endif %}
        {% for comment in comments %}
        <div class="media mb-4">
          {% if comment.user.profile.photo %}
          <img class="d-flex mr-3 rounded-circle" width="50px" height="50px" src="/media/{{ comment.user.profile.photo }}" alt="">
          {% else %}
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          {% endif %}
          <div class="media-body">
            <h5 class="mt-0">{{comment.user.username}}</h5>
            {{comment.comment}}
          </div>
        </div>
        {% endfor %}
      </div> {% endcomment %}
{% endblock %}

simple_blog/templates/posts/noticias.html
{% extends "base.html" %}
{% block title %}Noticias{% endblock title %}
{% block content %}

<!-- Older posts -->
<section class="older-posts section">

  <div class="container">
    
    <h2 class="title section-title" data-name="Noticias antiguas">Noticias</h2>
    
    <div class="older-posts-grid-wrapper d-grid">
      
      {% for post in posts %}
                    
                    <a href="{% url 'posts:detail' post.url %}" class="article d-grid">
                        
                        <div class="older-posts-article-image-wrapper">
                            <img src="{{ post.image_header.url }}" alt="" class="article-image">
                        </div>
                        
                        <div class="article-data-container" >
                            
                            <div class="article-data">
                                
                                <span class="article-date">{{post.created}}</span>
                            </div>
                            <h3 class="title article-title">{{post.title}}</h3>
                            <p class="article-description">{{post.post|safe|truncatechars:100}}</p>
                        </div>
                    </a>
                    {% endfor %}

    </div>
   
     
     
      <ul class="pagination-container">
        <li class="btn pagination-btn-left place-items-center">
          <div class="i ri-arrow-left-s-line"></div><a class="page-link" href="#">Newer</a>
        </li>
        <li class="btn pagination-btn-right place-items-center disabled">
          <a class="page-link" href="#">Older</a><div class="i ri-arrow-right-s-line"></div>
        </li>
      </ul>

  </div>
</section>

      {% endblock content %}