simple_blog/posts/urls.py
"""Posts URLs."""

# Django
from django.urls import path


# Views
from posts import views

urlpatterns = [
    path(
        route='noticias',
        view=views.PostsFeedView.as_view(template_name='noticias.html'),
        name='noticias'
    ),

    path(
        route='',
        view=views.PostsFeedView.as_view(template_name='index.html'),
        name='index'
    ),
    path(
        route='posts/<slug:url>/',
        view=views.PostDetailView.as_view(),
        name='detail'
    ),
    path(
        route='posts/save_comment',
        view=views.save_comment,
        name='save_comment'
    ),

]

simple_blog/simple_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings
from posts.views import searchBlog


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path(
        route='noticias',
        view=TemplateView.as_view(template_name='noticias.html'),
        name='noticias'
    ),
    path(
        route='',
        view=TemplateView.as_view(template_name='index.html'),
        name='index'
    ),
    path(
        route='institucional',
        view=TemplateView.as_view(template_name='about.html'),
        name='about'
    ),
    path(
        route='categorias',
        view=TemplateView.as_view(template_name='categorias.html'),
        name='categorias'
    ),
    path(
        route='contacto',
        view=TemplateView.as_view(template_name='contacto.html'),
        name='contacto'
    ),
    path('', include(('users.urls', 'users'), namespace='users')),

    path("q/", searchBlog, name='search'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simple_blog/users/urls.py
"""Users URLs."""

# Django
from django.urls import path
from django.views.generic import TemplateView

# View
from users import views

urlpatterns = [
    path(
        route='login',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='registro',
        view=views.SignupView.as_view(),
        name='register'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='registro_completado/',
        view=TemplateView.as_view(template_name='users/registerok.html'),
        name='registerok'
    ),
]

simple_blog/templates/base.html
<!DOCTYPE html>
<html lang="es" dir="ltr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Fuente 'Lato' -->
        <link rel="stylesheet" href="https://fonts.google.com/specimen/Lato?selection.family=Lato:wght@400;900">
        <!-- Icono de la organizacion -->
        <link rel="icon" href="../static/images/cropped-Logo-Curvas-01-tag.png" sizes="32x32"/>
        <!-- Remix icons -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css">
        {% load static %}
        <!-- Custon Styles -->
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <title> {% block title %}{% endblock title %}</title>
    </head>
    <body>
      <!-- Header -->
      <header class="header" id="header">

          <nav class="navbar container">

              <a href="{% url 'index' %}">
                  <img src="../static/images/Logo-Curvas-hor-02-303x119.png" alt="">
                  <h2 class="logo">Blog de noticias</h2>
              </a>
              <div class="menu" id="menu">
                  <ul class="list">
                    <li class="list-item">
                          <a href="{% url 'posts:index' %}" class="list-link current">Home</a>
                    </li>
                    <li class="list-item">
                          <a href="{% url 'about' %}" class="list-link">Institucional</a>
                    </li>
                    <li class="list-item">
                          <a href="{% url 'posts:noticias' %}" class="list-link">Noticias</a>
                    </li>
                    <li class="list-item">
                          <a href="{% url 'categorias' %}" class="list-link">Categorías</a>
                    </li>
                    <li class="list-item">
                        <a href="{% url 'contacto' %}" class="list-link">Contacto</a>
                    </li>
                    {% comment %} <li class="list-item">
                        <a href="{% url 'users:login' %}" class="list-link screen-lg-hidden">Acceder</a>
                    </li>
                    <li class="list-item screen-lg-hidden">
                        <a href="{% url 'users:register' %}" class="list-link">Registrarse</a>
                    </li> {% endcomment %}
                    {% if user.is_authenticated %}
                    <li class="list-item">
                        <a class="list-link screen-lg-hidden" data-toggle="dropdown" href="#" role="button" >{{request.user.username}}</a>
                        <div class="dropdown-menu">
                        {% if  user.is_staff %}
                        <a class="list-item screen-lg-hidden" href="{% url 'admin:index' %}">Administración</a>
                        {% endif %}
                        <a class="list-link screen-lg-hidden" href="{% url 'users:logout' %}">Salir</a>
                        </div>
                    </li>
                    
                    
                    {% else %}
                    <li class="list-item">
                        <a class="list-link screen-lg-hidden" href="{% url 'users:login' %}">Acceder</a>
                    </li>
                    <li class="list-item screen-lg-hidden">
                        <a class="list-link" href="{% url 'users:register' %}" >Registrarse</a>
                    </li>
                  {% endif %}
                      

                  </ul>
              </div>

              <div class="list list-right">
                  <button class="btn place-items-center" id="theme-toggle-btn">
                      <i class="ri-sun-line sun-icon"></i>
                      <i class="ri-moon-line moon-icon"></i>
                  </button>

                  <button class="btn place-items-center" id="search-icon-btn">
                      <i class="ri-search-line"></i>
                  </button>

                  <button class="btn place-items-center screen-lg-hidden menu-toggle-icon" id="menu-toggle-icon">
                      <i class="ri-menu-3-line open-menu-icon"></i>
                      <i class="ri-close-line close-menu-icon"></i>
                  </button>

                
                  {% if user.is_authenticated %}
                    <li class="list-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button">{{request.user.username}}</a>
                        <div class="dropdown-menu">
                        {% if  user.is_staff %}
                        <a class="list-link" href="{% url 'admin:index' %}">Administración</a>
                        {% endif %}
                        <a class="list-link" href="{% url 'users:logout' %}">Salir</a>
                        </div>
                    </li>
                    
                    
                    {% else %}
                    <a href="{% url 'users:login' %}" class="list-link screen-sm-hidden">Acceder</a>
                  <a href="{% url 'users:register' %}" class="list-link screen-sm-hidden btn sign-up-btn fancy-border">
                      <span>Registrarse</span>
                  </a>
                  {% endif %}
              </div>
          </nav>
      </header>

      <!-- Buscar -->
      <div class="search-form-container container" id="search-form-container">

          <div class="form-container-inner">

              <form action="{% url 'search' %}" method="GET" role="form" class="form">
                <script async src="https://cse.google.com/cse?cx=8118cc08d49854744">
                </script>
                  <input type="text" name="search" class="form-input" placeholder="Buscar">
                  <button class="btn form-btn" type="submit">
                      <i class="ri-search-line"></i>
                  </button>
              </form>
              <span class="form-note">Presiona ESC para cerrar.</span>
          </div>

          <button class="btn form-close-btn place-items-center" id="form-close-btn">
              <i class="ri-close-line"></i>
          </button>
      </div>
      
        {% block content %}
        
        {% endblock content %}
      <!-- Footer -->
        <footer class="footer section">

            <div class="footer-container container d-grid">

                <div class="company-data">
                    <a href="{% url 'about' %}">
                        <h2 class="logo-footer">Instituto Barranqueras</h2>
                    </a>
                    <p class="company-description">
                        Somos el primer instituto de nivel terciario de la localidad de Barranqueras.<br>
                        Apostamos a la transformación comunitaria de nuestra localidad.</p>
                    
                    <ul class="list social-media">
                        <h4>SEGUINOS EN NUESTRAS REDES</h4>
                        <li class="list-item">
                            <a href="https://www.instagram.com/institutobarranqueras/" class="list-link">
                                <i class="ri-instagram-line"></i>
                            </a>
                            <a href="https://www.facebook.com/institutobarranqueras" class="list-link">
                                <i class="ri-facebook-circle-line"></i>
                            </a>
                        </li>
                        <h4 class="list social-media">ENCONTRANOS</h4>
                        <ul class="list footer-list">
                            <li class="list-item">
                                <a href="https://goo.gl/maps/Ly9HPmB5wYVwkKW99" class="list-link">Diagonal Eva Perón 425 – Barranqueras</a>
                            </li>
                    </ul>
                </div>

                <div>
                    <h6 class="title footer-title">Categorías</h6>

                    <ul class="list footer-list">
                        <li class="list-item">
                            <a href="#" class="list-link">Ejemplo</a>
                        </li>
                    </ul>
                </div>
            </div>
        </footer>


<!-- Swiper.js Styles -->
<script src="./assets/js/swiper-bundle.min.js"></script>
<!-- Custom script Styles -->
<script src=".\assets\js\main.js"></script>
    </body>
        <script src="{% static 'js/main.js' %}"></script>
</html> 

simple_blog/templates/categorias.html
{% extends 'base.html' %}
{% block title %}Sobre Nosotros{% endblock title %}
{% block content %}

            <!-- Categorías -->
    <section class="popular-tags section">

        <div class="container">

            <h2 class="title section-title" data-name="Categorías">Categorías</h2>

            <div class="popular-tags-container d-grid">

                <a href="#" class="article">
                    <span class="tag-name">#Inscripción</span>
                    <img src="../static/images/categories/inscripcion.jpg" alt="" class="article-image">
                </a>

                <a href="#" class="article">
                    <span class="tag-name">#Convenios</span>
                    <img src="../static/images/categories/convenios.jpg" alt="" class="article-image">
                </a>

                <a href="#" class="article">
                    <span class="tag-name">#Depostes</span>
                    <img src="../static/images/categories/deportes.jpg" alt="" class="article-image">
                </a>

                <a href="#" class="article">
                    <span class="tag-name">#Actividades</span>
                    <img src="../static/images/categories/actividades.jpg" alt="" class="article-image">
                </a>

                <a href="#" class="article">
                    <span class="tag-name">#Programación</span>
                    <img src="../static/images/categories/programacion.jpg" alt="" class="article-image">
                </a>

                <a href="#" class="article">
                    <span class="tag-name">#Cursos</span>
                    <img src="../static/images/categories/cursos.jpg" alt="" class="article-image">
                </a>

            </div>

        </div>
    </section>


{% endblock content %}

simple_blog/templates/contacto.html
{% extends 'base.html' %}
{% block title %}Sobre Nosotros{% endblock title %}
{% block content %}

        <!-- Blog company data -->
        <section class="blog-post section-header-offset">

            <div class="blog-post-container container">

                <div class="blog-company-data d-grid">
                    <h2 class="title blog-post-title">Contactate con nosotros!</h2> 
                    {% comment %} <img class="company-data-image" src="../static/images/foto-frente-2.jpg" alt=""> {% endcomment %}
                </div>

                <div class="container">
                        
                    <p>Podés comunicarte con nosotros a través de nuestro <strong>WhatsApp</strong> al <a href="https://api.whatsapp.com/send?phone=5493624250382&amp;text=Hola">+54 9 362 425 0382</a> o haciendo click en el logo:
                        <a href="https://api.whatsapp.com/send?phone=5493624250382&amp;text=Hola" target="_blank">
                            <div class="btn-whatsapp">
                                <img src="../static/images/download.svg">
                            </div>
                        </a>
                    </p>
                        
                    <p>Por <strong>e-mail</strong> a la dirección <strong><a href="mailto:uep161info@educ.ar">uep161info@educ.ar</a></strong></p>
                        
                    <p>Para más información podés acceder a nuestro sitio web <a href="http://www.institutobarranqueras.com">www.institutobarranqueras.com</a></p>    
                    
                    <p>Nuestras redes sociales: <a href="https://www.facebook.com/institutobarranqueras">Facebook</a> e <a href="https://www.instagram.com/institutobarranqueras/">Instagram</a>.</p>
                
                </div>
                
            </div>
        </section>

{% endblock content %}



<!-- Box para whatsapp -->

simple_blog/templates/index.html
{% extends 'base.html' %}
{% block title %}Instituto Barranqueras - Blog{% endblock title %}
{% block content %}

        <!-- Featured articles -->
        <section class="featured-articles section-header-offset">

            <div class="featured-articles-container container d-grid">

                <div class="featured-content d-grid">

                    <div class="headline-banner">
                        <h3 class="headline fancy-border">
                            <span class="place-items-center">Noticias Destacadas</span>
                        </h3>
                        <span class="headline-description">Enterate de lo que está pasando en el IB!</span>
                    </div>

                    <a href="posts/el-instituto-barranqueras-y-el-instituto-de-agricultura-familiar-popular-firman-convenio/" class="article featured-article featured-article-1">
                        <img src="../static/images/featured/featured-1.jpg" alt="" class="article-image">
                        <span class="article-category">Convenios</span>

                        <div class="article-data-container">

                            <div class="article-data">
                                <span class="article-date">09 Ago 2022</span>
                            </div>
                            <h3 class="title article-title">El instituto Barranqueras y el Instituto de Agricultura Familiar Popular firman convenio</h3>
                        </div>
                    </a>

                    <a href="posts/continua-la-muestra-fotografica-vivir-en-humedales-en-barranqueras/" class="article featured-article featured-article-2">
                        <img src="../static/images/featured/featured-2.jpg" alt="" class="article-image">
                        <span class="article-category">Actividades</span>

                        <div class="article-data-container">

                            <div class="article-data">
                                <span class="article-date">13 Ago 2022</span>
                            </div>
                            <h3 class="title article-title">Continúa la Muestra Fotográfica "Vivir en Humedales" en Barranqueras</h3>
                        </div>
                    </a>

                    <a href="posts/el-instituto-barranqueras-mantiene-abierta-la-inscripcion-para-el-ciclo-lectivo-2022/" class="article featured-article featured-article-3">
                        <img src="../static/images/featured/featured-3.jpg" alt="" class="article-image">
                        <span class="article-category">Inscripciones</span>

                        <div class="article-data-container">

                            <div class="article-data">
                                <span class="article-date">16 Feb 2022</span>
                            </div>
                            <h3 class="title article-title">El Instituto Barranqueras mantiene abierta la inscripción para el Ciclo Lectivo 2022</h3>
                        </div>
                    </a>
                </div>
                <!-- Sidebar-->
                <div class="sidebar d-grid">

                    <h3 class="title featured-content-title">Noticias Populares</h3>

                    <a href="posts/el-instituto-barranqueras-mantiene-abierta-la-inscripcion-para-el-ciclo-lectivo-2022/" class="trending-news-box">
                        <div class="trending-news-image-box">
                            <span class="trending-number place-items-center">01</span>
                            <img src="../static/images/trending/trending-1.jpg" alt="" class="article-image">
                        </div>

                        <div class="trending-news-data">
                            <div class="article-data">
                                <span class="article-date">16 Feb 2022</span>
                            </div>
                            
                            <h3 class="title article-title">El Instituto Barranqueras mantiene abierta la inscripción para el Ciclo Lectivo 2022</h3>
                        </div>
                    </a>

                    <a href="posts/magda-ayala-participo-del-4-foro-de-desarrollo-sustentable/" class="trending-news-box">
                        <div class="trending-news-image-box">
                            <span class="trending-number place-items-center">02</span>
                            <img src="../static/images/trending/trending-2.jpg" alt="" class="article-image">
                        </div>

                        <div class="trending-news-data">
                            <div class="article-data">
                                <span class="article-date">08 Nov 2020</span>
                            </div>
                            
                            <h3 class="title article-title">Magda Ayala participó del 4° Foro de Desarrollo Sustentable</h3>
                        </div>
                    </a>

                    <a href="posts/continua-la-muestra-fotografica-vivir-en-humedales-en-barranqueras/" class="trending-news-box">
                        <div class="trending-news-image-box">
                            <span class="trending-number place-items-center">03</span>
                            <img src="../static/images/trending/trending-3.jpg" alt="" class="article-image">
                        </div>

                        <div class="trending-news-data">
                            <div class="article-data">
                                <span class="article-date">13 Ago 2022</span>
                            </div>
                            
                            <h3 class="title article-title">Continúa la Muestra Fotográfica "Vivir en Humedales" en Barranqueras</h3>
                        </div>
                    </a>

                    <a href="#" class="trending-news-box">
                        <div class="trending-news-image-box">
                            <span class="trending-number place-items-center">04</span>
                            <img src="../static/images/trending/trending-4.jpg" alt="" class="article-image">
                        </div>

                        <div class="trending-news-data">
                            <div class="article-data">
                                <span class="article-date">14 Ago 2022</span>
                            </div>
                            
                            <h3 class="title article-title">Otra noticia</h3>
                        </div>
                    </a>
                    <a href="#" class="trending-news-box">
                      <div class="trending-news-image-box">
                          <span class="trending-number place-items-center">05</span>
                          <img src="../static/images/trending/trending-5.jpg" alt="" class="article-image">
                      </div>

                      <div class="trending-news-data">
                          <div class="article-data">
                              <span class="article-date">14 Ago 2022</span>
                          </div>
                          
                          <h3 class="title article-title">Otra noticia</h3>
                      </div>
                  </a>
                </div>
            </div>
        </section>

        <!-- Quick read -->
        
        <!-- Older posts -->
        <section class="older-posts section">

            <div class="container">

                <h2 class="title section-title" data-name="Noticias antiguas">Noticias Antiguas</h2>

                <div class="older-posts-grid-wrapper d-grid">
                    
                    {% for post in posts %}
                    
                    <a href="{% url 'posts:detail' post.url %}" class="article d-grid">
                        
                        <div class="older-posts-article-image-wrapper">
                            <img src="{{ post.image_header.url }}" alt="" class="article-image">
                        </div>
                        
                        <div class="article-data-container" >
                            
                            <div class="article-data">
                                
                                <span class="article-date">{{post.created}}</span>
                            </div>
                            <h3 class="title article-title">{{post.title}}</h3>
                            <p class="article-description">{{post.post|safe|truncatechars:100}}</p>
                        </div>
                    </a>
                    {% endfor %}
                </div>

                <div class="see-more-container">
                    <a href="{% url 'noticias' %}" class="btn see-more-btn place-items-center">
                        Ver más <div class="i ri-arrow-right-s-line"></div>
                    </a>
                </div>
            </div>
        </section>
        <!-- Popular tags -->
        <!-- <section class="popular-tags section">

            <div class="container">

                <h2 class="title section-title" data-name="Etiquetas populares">Etiquetas Populares </h2>
                    <a href="#" class="article">
                        <span class="tag-name">#viajes</span>
                        <img src="" alt="" class="article-image">
                    </a>
                <div class="popular-tags-container d-grid">

                </div>
            </div>
        </section> -->


{% endblock content %}

simple_blog/templates/noticias.html
{% extends "base.html" %}
{% block title %}Noticias{% endblock title %}
{% block content %}

<!-- Older posts -->
<section class="older-posts section">
  
  <div class="container">
    
    <h2 class="title section-title" data-name="Noticias antiguas">Noticias</h2>
    
    <div class="older-posts-grid-wrapper d-grid">
      
      {% for post in posts %}
                    
                  <a href="{% url 'posts:detail' post.url %}" class="article d-grid">
                    
                    <div class="older-posts-article-image-wrapper">
                      <img src="{{ post.image_header.url }}" alt="" class="article-image">
                    </div>
                    
                    <div class="article-data-container" >
                      
                      <div class="article-data">
                        
                        <span class="article-date">{{post.created}}</span>
                      
                      </div>
                      
                      <h3 class="title article-title">{{post.title}}</h3>
                      <p class="article-description">{{post.post|safe|truncatechars:100}}</p>
                    </div>
                  </a>
      {% endfor %}

    </div>
   
     
     
      <ul class="pagination-container">
        <li class="btn pagination-btn-left place-items-center">
          <div class="i ri-arrow-left-s-line"></div><a class="page-link" href="#">Newer</a>
        </li>
        <li class="btn pagination-btn-right place-items-center disabled">
          <a class="page-link" href="#">Older</a><div class="i ri-arrow-right-s-line"></div>
        </li>
      </ul>

  </div>
</section>

      {% endblock content %}

simple_blog/templates/search-results.html
{% extends 'base.html' %}
{% block title %}Sobre Nosotros{% endblock title %}
{% block content %}

        <!-- Blog company data -->
        <section class="blog-post section-header-offset">

            <div class="blog-post-container container">

                <div class="container">
                        
                    <ul>
                        {% for element in results %}
                            <li>{{ element }}</li>
                        {% endfor %}
                        </ul>
                
                </div>
            </div>
        </section>

{% endblock content %}